import 'dart:async' show Future;
import 'package:flutter/services.dart' show rootBundle;
import 'package:mysql1/mysql1.dart';
import 'package:predizione/Services/weightKey.dart';
import 'League.dart';
import 'Match.dart';
import 'Accuracy.dart';
import 'Odd.dart';
import 'Prediction.dart';
class database {


  Result rfromS(String s){
    if(s=="F"){return Result.EMPTY;}
    if(s=="H"){return Result.H;}
    if(s=="D"){return Result.D;}
    else{return Result.A;}
  }
  Prediction matchList(Prediction pd,String Leaguen){
    List<Match> Matches=new List<Match>();

    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Tophane',1,5,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Deredibi',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Parlakspor',3,3,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Odunhane',3,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Peynirdibi',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Nehirdibi',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Kurtspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Buzspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Totemspor',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Villadibi',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Altinsaray',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Denizspor',0,5,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Zarhane',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Eskikapi',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Halterspor',0,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Kumspor',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Tankspor',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Parlakspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Buzspor',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Hedefspor',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Peynirdibi',2,3,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Odunhane',0,4,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Deredibi',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Nehirdibi',3,2,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Kurtspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Halterspor',0,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Villadibi',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Eskikapi',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Zarhane',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Denizspor',2,2,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Altinsaray',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Totemspor',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Tankspor',3,3,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Tophane',0,3,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Kumspor',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Eskikapi',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Buzspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Halterspor',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Hedefspor',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Kurtspor',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Peynirdibi',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Parlakspor',2,2,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Odunhane',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Deredibi',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Hedefspor',3,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Denizspor',3,2,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Nehirdibi',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Altinsaray',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Zarhane',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Totemspor',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Kumspor',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Villadibi',4,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Tankspor',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Tophane',3,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Kurtspor',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Totemspor',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Peynirdibi',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Halterspor',0,4,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Parlakspor',3,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Hedefspor',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Eskikapi',3,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Odunhane',2,3,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Tankspor',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Kumspor',0,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Denizspor',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Altinsaray',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Kurtspor',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Zarhane',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Deredibi',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Nehirdibi',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Tophane',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Buzspor',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Eskikapi',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Hedefspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Halterspor',2,2,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Villadibi',4,3,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Totemspor',1,3,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Parlakspor',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Odunhane',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Buzspor',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Peynirdibi',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Tankspor',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Deredibi',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Altinsaray',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Nehirdibi',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Parlakspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Tophane',0,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Zarhane',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Kumspor',0,4,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Kurtspor',3,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Hedefspor',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Villadibi',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Buzspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Halterspor',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Peynirdibi',1,3,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Odunhane',1,4,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Eskikapi',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Totemspor',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Denizspor',2,3,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Odunhane',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Tankspor',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Parlakspor',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Tophane',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Kurtspor',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Altinsaray',3,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Deredibi',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Nehirdibi',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Peynirdibi',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Halterspor',0,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Villadibi',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Eskikapi',3,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Denizspor',1,4,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Kumspor',2,2,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Totemspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Hedefspor',3,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Buzspor',0,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Kurtspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Tophane',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Odunhane',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Parlakspor',3,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Altinsaray',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Tankspor',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Peynirdibi',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Deredibi',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Zarhane',3,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Buzspor',0,3,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Eskikapi',2,2,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Kumspor',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Villadibi',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Totemspor',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Zarhane',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Denizspor',0,1,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Hedefspor',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Halterspor',0,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Tankspor',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Nehirdibi',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Parlakspor',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Peynirdibi',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Deredibi',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Kurtspor',2,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Odunhane',0,4,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Tophane',1,0,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Buzspor',1,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Totemspor',1,1,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Denizspor',0,0,rfromS('D')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Eskikapi',2,1,rfromS('H')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Altinsaray',0,2,rfromS('A')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Nehirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Kumspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Hedefspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Zarhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Halterspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Villadibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Tankspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Zarhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Altinsaray',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Villadibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Halterspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Totemspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Kumspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Eskikapi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Denizspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Odunhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Peynirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Deredibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Tophane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Parlakspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Nehirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Hedefspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Buzspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Kurtspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Altinsaray',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Tophane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Tankspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Totemspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Denizspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Zarhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Kumspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Villadibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Eskikapi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Kurtspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Buzspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Hedefspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Nehirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Deredibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Halterspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Odunhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Peynirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Parlakspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Tankspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Nehirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Denizspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Altinsaray',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Tophane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Zarhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Villadibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Kumspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Totemspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Parlakspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Eskikapi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Halterspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Deredibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Odunhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Kurtspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Buzspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Peynirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Hedefspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Nehirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Villadibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Deredibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Zarhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Tankspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Altinsaray',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Denizspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Tophane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Kumspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Peynirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Odunhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Buzspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Halterspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Totemspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Hedefspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Eskikapi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Parlakspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Villadibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Zarhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Denizspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Altinsaray',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Nehirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Tophane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Kumspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Deredibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Tankspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Kurtspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Hedefspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Buzspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Halterspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Eskikapi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Villadibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Odunhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Denizspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Peynirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Totemspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Altinsaray',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Zarhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Kumspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Tankspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Kurtspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Nehirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Tophane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Parlakspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Deredibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Totemspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Peynirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Eskikapi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Villadibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Denizspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Buzspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Kumspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Hedefspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Halterspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Parlakspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Tophane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Tankspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Nehirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Odunhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Deredibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Kurtspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Zarhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Altinsaray',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Denizspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Villadibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Kumspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Totemspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Zarhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Halterspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Hedefspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Eskikapi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Buzspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Kurtspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Deredibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Nehirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Odunhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Tophane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Peynirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Altinsaray',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Parlakspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Tankspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tophane','Halterspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Parlakspor','Eskikapi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Nehirdibi','Villadibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Tankspor','Zarhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kurtspor','Denizspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Peynirdibi','Kumspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Deredibi','Totemspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Buzspor','Hedefspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Odunhane','Altinsaray',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Totemspor','Nehirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Villadibi','Buzspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Altinsaray','Tankspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Denizspor','Deredibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Hedefspor','Parlakspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Zarhane','Kurtspor',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Eskikapi','Odunhane',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Halterspor','Peynirdibi',0,0,rfromS('F')));
    Matches.add(Match(2020,'Mahalle Ligi','Türkiye',1,'Kumspor','Tophane',0,0,rfromS('F')));


    pd.Matches=Matches;
    pd.CurrentLeague=new League();
    pd.CurrentLeague.leagueName=Leaguen;
    return pd;



  }
  List<Odd> betOdds(){
    List<Odd> Odds=new List<Odd>();
    Odds.add(Odd(0.02,0.26));
    Odds.add(Odd(0.03,0.26));
    Odds.add(Odd(0.04,0.26));
    Odds.add(Odd(0.05,0.26));
    Odds.add(Odd(0.06,0.26));
    Odds.add(Odd(0.07,0.26));
    Odds.add(Odd(0.08,0.26));
    Odds.add(Odd(0.09,0.26));
    Odds.add(Odd(0.1,0.26));
    Odds.add(Odd(0.11,0.26));
    Odds.add(Odd(0.12,0.26));
    Odds.add(Odd(0.13,0.26));
    Odds.add(Odd(0.14,0.26));
    Odds.add(Odd(0.15,0.26));
    Odds.add(Odd(0.16,0.26));
    Odds.add(Odd(0.17,0.26));
    Odds.add(Odd(0.18,0.26));
    Odds.add(Odd(0.19,0.26));
    Odds.add(Odd(0.2,0.26));
    Odds.add(Odd(0.21,0.26));
    Odds.add(Odd(0.22,0.26));
    Odds.add(Odd(0.23,0.26));
    Odds.add(Odd(0.24,0.26));
    Odds.add(Odd(0.25,0.26));
    Odds.add(Odd(0.26,0.26));
    Odds.add(Odd(0.27,0.26));
    Odds.add(Odd(0.28,0.26));
    Odds.add(Odd(0.29,0.26));
    Odds.add(Odd(0.3,0.26));
    Odds.add(Odd(0.31,0.26));
    Odds.add(Odd(0.32,0.26));
    Odds.add(Odd(0.33,0.26));
    Odds.add(Odd(0.34,0.26));
    Odds.add(Odd(0.35,0.26));
    Odds.add(Odd(0.36,0.26));
    Odds.add(Odd(0.37,0.26));
    Odds.add(Odd(0.38,0.26));
    Odds.add(Odd(0.39,0.26));
    Odds.add(Odd(0.4,0.26));
    Odds.add(Odd(0.41,0.26));
    Odds.add(Odd(0.42,0.26));
    Odds.add(Odd(0.43,0.26));
    Odds.add(Odd(0.44,0.26));
    Odds.add(Odd(0.45,0.26));
    Odds.add(Odd(0.46,0.26));
    Odds.add(Odd(0.47,0.26));
    Odds.add(Odd(0.48,0.26));
    Odds.add(Odd(0.49,0.26));
    Odds.add(Odd(0.5,0.26));
    Odds.add(Odd(0.51,0.26));
    Odds.add(Odd(0.52,0.26));
    Odds.add(Odd(0.53,0.25));
    Odds.add(Odd(0.54,0.25));
    Odds.add(Odd(0.55,0.25));
    Odds.add(Odd(0.56,0.25));
    Odds.add(Odd(0.57,0.25));
    Odds.add(Odd(0.58,0.25));
    Odds.add(Odd(0.59,0.25));
    Odds.add(Odd(0.6,0.24));
    Odds.add(Odd(0.61,0.24));
    Odds.add(Odd(0.62,0.24));
    Odds.add(Odd(0.63,0.24));
    Odds.add(Odd(0.64,0.24));
    Odds.add(Odd(0.65,0.23));
    Odds.add(Odd(0.66,0.23));
    Odds.add(Odd(0.67,0.23));
    Odds.add(Odd(0.68,0.23));
    Odds.add(Odd(0.69,0.22));
    Odds.add(Odd(0.7,0.22));
    Odds.add(Odd(0.71,0.22));
    Odds.add(Odd(0.72,0.21));
    Odds.add(Odd(0.73,0.21));
    Odds.add(Odd(0.74,0.20));
    Odds.add(Odd(0.75,0.20));
    Odds.add(Odd(0.76,0.20));
    Odds.add(Odd(0.77,0.19));
    Odds.add(Odd(0.78,0.19));
    Odds.add(Odd(0.79,0.18));
    Odds.add(Odd(0.8,0.18));
    Odds.add(Odd(0.81,0.17));
    Odds.add(Odd(0.82,0.17));
    Odds.add(Odd(0.83,0.16));
    Odds.add(Odd(0.84,0.16));
    Odds.add(Odd(0.85,0.15));
    Odds.add(Odd(0.86,0.14));
    Odds.add(Odd(0.87,0.14));
    Odds.add(Odd(0.88,0.13));
    Odds.add(Odd(0.89,0.12));
    Odds.add(Odd(0.9,0.12));
    Odds.add(Odd(0.91,0.11));
    Odds.add(Odd(0.92,0.10));
    Odds.add(Odd(0.93,0.09));
    Odds.add(Odd(0.94,0.08));
    Odds.add(Odd(0.95,0.06));
    Odds.add(Odd(0.96,0.06));
  return Odds;

  }
  void uploadStandings(League a){//for(int i=0;i<a.Teams.length;i++){print(i.toString()+" "+a.Teams[i].teamName+" "+a.Teams[i].totalMatch.toString()+" "+a.Teams[i].points.toString());}
    }
  void uploadResults(League a){
    //for(int i=0;i<a.Results.length;i++){print(i.toString()+" "+a.Results[i].homeTeam+" "+a.Results[i].awayTeam+" "+(a.Results[i].result==a.Results[i].machinePredict).toString());}
    }
  void uploadAccuracy(Accuracy acc){}
  List<Accuracy> keyList(){
    List<Accuracy> wk=new List<Accuracy>();
    // Liga NOS %58 Home:143.63636363636363 Draw:103.94736842105263 Away:100.0 powerRank:-2.0 resultPerc:-3.0 pyEx:9.0 pyExSide:1.0 pattern1:0.0 pattern3:0.0 pattern5:0.0
    // La Liga Home:313.7857142857143 Draw:292.15189873417717 Away:274.30379746835445 powerRank:6.0 resultPerc:-6.0 pyEx:-8.0 pyExSide:3.0 pattern1:0.0 pattern3:0.0 pattern5:0.0
    return wk;
  }


    Prediction loadDatabase(){
    Prediction pd=new Prediction();
    pd.betOdds= betOdds();
    pd.Keylist= keyList();

    return pd;
  }
}
